security:
    encoders:
        Pohy\QuoteBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        doctrine:
            entity:
                class: Pohy\QuoteBundle\Entity\User
                property: username

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: quote_login
                check_path: quote_login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/quote/view, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/quote, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
